uploads = []
generated = []

[[outputs]]
id = "GyZ3ZeuK780YWqW6zjmDU"
uri = "file://coinhub-standalone.zip"
type = "unspecified"
title = "CoinHub — Standalone HTML (ZIP)"

[[outputs]]
id = "9D1sSOC6NrEHbu56Rj7-H"
uri = "file://coinhub-html.zip"
type = "unspecified"
title = "CoinHub — Standalone HTML/CSS/JS (indirip açyp işlediň)"

[[outputs]]
id = "fqb1lhd8MInOsoH6OnXu6"
uri = "file://coinhub-files.zip"
type = "unspecified"
title = "CoinHub — index.html + style.css + app.js"
